name: Flutter build Apk
on: [push]
jobs:
    CreateApk:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v1

        - name: Set Flutter
          uses: subosito/flutter-action@v1
          with:
            flutter-version: '3.19'
        
        - name: Clean Build
          run: flutter clean

        - name: Get Dependencies
          run: flutter pub get
        
        - name: Build Apk
          run: flutter build apk --split-per-abi
          
