name: Flutter build Apk
on: [push]
jobs:
    CreateApk:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v1

        - name: Set Flutter
          uses: subosito/flutter-action@v1
          with:
            flutter-version: '3.19'
        
        - name: Clean Build
          run: flutter clean

        - name: Get Dependencies
          run: flutter pub get
        
        - name: Build Apk
          run: flutter build apk --split-per-abi

        
        # - name: Archieve-Apk-Releases
        #   uses: actions/upload-artifact@v1
        #   with:
        #     name: Releases-Apks
        #     path:
        #         build\app\outputs\flutter-apk\app-armeabi-v7a-release.apk
        #         build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
        #         # build/app/outputs/flutter-apk/app-x86_64-release.apk
        - name: Release the Apk
          uses: actions/create-release@v1
          env:
            GITHUB-TOKEN: ${{secrets.TOKEN_JP_BOOK}}
          with:
            tag_name: ${{steps.version.outputs.version}}
            release_name: Release ${{steps.version.outputs.version}}
            body:
               Release Notes Go Here
            draft: false
            prerelease: false
                 
            
        - name: Upload APK
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_JP_BOOK }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./build/app/outputs/flutter-apk/app-release.apk
            asset_name: app-${{ steps.version.outputs.version }}.apk
            asset_content_type: application/vnd.android.package-archive

            
