name: JP Book Workflow
on:
  push:
    branches:
      main
      master

jobs:
  Make-Apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.19

      - name: Clean Gradle Build
        run: flutter clean

      - name: Getting Dependencies
        run: flutter pub get

      - name: Build Apk
        run: flutter build apk --release

      - name: Releaset the Apk
        uses: ncipollo/release-action@v1
        with:
          tag: v1.1.${{ github.run_number }}
          token: ${{ secrets.JP_BOOK_TOKEN }}